import { useEffect, useMemo, useRef, useState } from 'react';
import axios from 'axios';
import { Search, Plus, Upload, UserRound, Image as ImageIcon, ChevronRight, X, Check, Trash2, Phone, ClipboardList, ScanLine } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { toast, Toaster } from 'sonner';
import './App.css';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const CONDITIONS = ['Alopecia','Dandruff / Seborrheic dermatitis','Psoriasis','Folliculitis','Healthy scalp','Needs review'];
const colors = {'Alopecia':'tag-rose','Dandruff / Seborrheic dermatitis':'tag-amber','Psoriasis':'tag-sky','Folliculitis':'tag-orange','Healthy scalp':'tag-teal','Needs review':'tag-slate'};
const initials = name => name?.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();

function App() {
  const [patients,setPatients]=useState([]), [selected,setSelected]=useState(null), [photos,setPhotos]=useState([]), [search,setSearch]=useState('');
  const [showNew,setShowNew]=useState(false), [form,setForm]=useState({name:'',phone:'',notes:''}), [loading,setLoading]=useState(true);
  const [tagFilter,setTagFilter]=useState('All conditions'); const fileRef=useRef();
  const fetchPatients=()=>axios.get(`${API}/patients`,{params:{search}}).then(r=>setPatients(r.data));
  const fetchPhotos=id=>axios.get(`${API}/patients/${id}/photos`).then(r=>setPhotos(r.data));
  useEffect(()=>{setLoading(true); fetchPatients().finally(()=>setLoading(false));},[search]);
  const openPatient=p=>{setSelected(p);fetchPhotos(p.id)};
  const addPatient=async e=>{e.preventDefault();if(!form.name||!form.phone)return;const r=await axios.post(`${API}/patients`,form);setForm({name:'',phone:'',notes:''});setShowNew(false);setPatients(x=>[r.data,...x]);openPatient(r.data);toast.success('Patient record created');};
  const upload=async e=>{const file=e.target.files?.[0];if(!file||!selected)return;const data=new FormData();data.append('file',file);data.append('conditions','Needs review');const r=await axios.post(`${API}/patients/${selected.id}/photos`,data);setPhotos(x=>[r.data,...x]);setSelected(x=>({...x,photo_count:x.photo_count+1,conditions:[...new Set([...x.conditions,'Needs review'])]}));toast.success('Photo saved — marked Needs review');e.target.value='';};
  const remove=async id=>{await axios.delete(`${API}/photos/${id}`);setPhotos(x=>x.filter(p=>p.id!==id));setSelected(x=>({...x,photo_count:Math.max(0,x.photo_count-1)}));toast.success('Photo removed');};
  const visible=useMemo(()=>tagFilter==='All conditions'?photos:photos.filter(p=>p.conditions.includes(tagFilter)),[photos,tagFilter]);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ScanLine size={22}/></div><div><b>trichocare</b><span>clinical workspace</span></div></div><div className="side-label">WORKSPACE</div><button className="nav-active" data-testid="patients-nav"><UserRound size={18}/> Patients <span>{patients.length}</span></button><div className="sidebar-foot"><div className="status-dot"/>All records are private<br/><small>Single-clinic workspace</small></div></aside>
  <main className="main"><header className="topbar"><div><p className="eyebrow">TRICHOLOGY / RECORDS</p><h1>Patient records</h1></div><Button data-testid="new-patient-button" onClick={()=>setShowNew(true)} className="primary-button"><Plus size={17}/> New patient</Button></header><section className="workspace-grid"><div className="patient-panel"><div className="panel-tools"><div className="search-wrap"><Search size={16}/><Input data-testid="patient-search-input" placeholder="Search patients..." value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="record-count" data-testid="patient-count">{patients.length} records</span></div><div className="patient-list" data-testid="patient-list">{loading?<div className="empty-state">Loading records...</div>:patients.length===0?<div className="empty-state"><UserRound size={28}/><b>No patients yet</b><span>Add your first patient to begin.</span></div>:patients.map(p=><button className={`patient-row ${selected?.id===p.id?'selected':''}`} data-testid={`patient-row-${p.id}`} key={p.id} onClick={()=>openPatient(p)}><div className="avatar">{initials(p.name)}</div><div className="patient-summary"><b>{p.name}</b><span>{p.phone}</span><div className="mini-tags">{p.conditions.slice(0,2).map(c=><i className={colors[c]} key={c}>{c}</i>)}</div></div><div className="row-meta"><span>{p.photo_count} <ImageIcon size={13}/></span><ChevronRight size={16}/></div></button>)}</div></div>
  <div className="detail-panel">{selected?<><div className="detail-head"><div><p className="eyebrow">PATIENT PROFILE</p><h2 data-testid="selected-patient-name">{selected.name}</h2><div className="contact"><span><Phone size={14}/>{selected.phone}</span><span><ClipboardList size={14}/>Added {new Date(selected.created_at).toLocaleDateString()}</span></div></div><div className="profile-avatar">{initials(selected.name)}</div></div><div className="notes-band"><div><span className="section-kicker">VISIT NOTES</span><p data-testid="patient-notes">{selected.notes||'No visit notes added yet.'}</p></div></div><div className="photos-head"><div><span className="section-kicker">DERMASCOPE IMAGES</span><h3>{photos.length} captured {photos.length===1?'image':'images'}</h3></div><input ref={fileRef} type="file" accept="image/*" onChange={upload} hidden/><Button data-testid="upload-photo-button" onClick={()=>fileRef.current?.click()} className="outline-button"><Upload size={16}/> Upload photo</Button></div><div className="filter-strip"><button className={tagFilter==='All conditions'?'filter-on':''} data-testid="condition-filter-all" onClick={()=>setTagFilter('All conditions')}>All</button>{CONDITIONS.map(c=><button key={c} className={tagFilter===c?'filter-on':''} data-testid={`condition-filter-${c.toLowerCase().replaceAll(' ','-').replaceAll('/','')}`} onClick={()=>setTagFilter(c)}>{c}</button>)}</div><div className="photo-grid" data-testid="photo-grid">{visible.length===0?<div className="empty-photos"><ImageIcon size={26}/><span>No images in this view</span></div>:visible.map(p=><div className="photo-card" data-testid={`photo-card-${p.id}`} key={p.id}><img src={p.data_url} alt={p.filename}/><div className="photo-info"><div>{p.conditions.map(c=><Badge className={colors[c]} key={c}>{c}</Badge>)}</div><button data-testid={`delete-photo-${p.id}`} onClick={()=>remove(p.id)} aria-label="Remove photo"><Trash2 size={15}/></button></div></div>)}</div></>:<div className="welcome"><div className="welcome-icon"><ScanLine size={32}/></div><h2>Your clinical workspace</h2><p>Select a patient to review their dermascope images, or create a new record to begin.</p><Button data-testid="welcome-new-patient-button" onClick={()=>setShowNew(true)} className="primary-button"><Plus size={17}/> Add first patient</Button></div>}</div></section></main>
  {showNew&&<div className="modal-backdrop" data-testid="new-patient-modal"><form className="modal" onSubmit={addPatient}><button type="button" className="close-button" data-testid="close-new-patient-button" onClick={()=>setShowNew(false)}><X size={18}/></button><p className="eyebrow">NEW RECORD</p><h2>Add a patient</h2><p className="modal-sub">Start a private clinical record for your next examination.</p><label>Full name<Input data-testid="patient-name-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Maya Patel"/></label><label>Phone number<Input data-testid="patient-phone-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="e.g. +1 555 010 2400"/></label><label>Visit notes <Textarea data-testid="patient-notes-input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Initial observations, concerns, or treatment context..."/></label><Button data-testid="save-patient-button" type="submit" className="primary-button modal-submit"><Check size={16}/> Save patient</Button></form></div>}<Toaster position="bottom-right"/></div>;
}
export default App;